---
-  #name: Reboot
  #become: True
  #reboot:
  #  reboot_timeout: 300
  #async: 1
  #poll: 0
  #when: sys.reboot
  #ignore_errors: True

#- name: execute reboot
#  shell:
#    cmd: "sleep 2 && reboot"
#  async: 1
#  poll: 0
#
#- name: Wait for SSH port down
#  become: no
#  wait_for:
#    #host: "{{ inventory_hostname }}"
#    host: all
#    port: "{{ ansible_ssh_port }}"
#    state: stopped
#  delegate_to: 127.0.0.1
#
#- name: Wait for SSH port up
#  become: no
#  wait_for_connection:
#    #host: "{{ inventory_hostname }}"
#    #host: all
#    #port: "{{ ansible_ssh_port }}"
#    delay: 3
#    connect_timeout: 3
#    timeout: 30
#    #state: started
#  delegate_to: 127.0.0.1
- name: restart machine
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  become: true
  ignore_errors: true

- name: wait for reboot
  wait_for_connection:
    delay: 30
    timeout: 300

- name: Debug
  debug:
    msg: Finish!
